"""Email delivery — send reports (and their PDFs) to stakeholders automatically.
Works over plain SMTP (stdlib `smtplib`, any provider) or a transactional API
(Resend / SendGrid) when a key is set. Degrades to a dry-run that tells you exactly
what would be sent and which credential to add. Site-agnostic.

    notify.email_report(cfg, "report.pdf")   # → recipients in cfg.report.email_to
    config: { "report": { "email_to": ["a@x.com"], "from": "seo@x.com" } }
    env (pick one): SMTP_HOST/SMTP_PORT/SMTP_USER/SMTP_PASSWORD · RESEND_API_KEY · SENDGRID_API_KEY
"""
import base64
import json
import os
import smtplib
import urllib.request
from email.message import EmailMessage
from pathlib import Path


def _recipients(cfg, to=None):
    r = to or (cfg.get("report", {}) or {}).get("email_to") or []
    return r if isinstance(r, list) else [r]


def _from(cfg):
    return (cfg.get("report", {}) or {}).get("from") or os.environ.get("SMTP_USER") or "seo-agent@localhost"


def send(cfg, to, subject, body, attachments=None):
    """Send an email with optional file attachments. Returns a result dict."""
    tos = _recipients(cfg, to)
    if not tos:
        return {"ok": False, "error": "no recipients — set report.email_to in config"}
    attachments = attachments or []
    if os.environ.get("RESEND_API_KEY"):
        return _resend(cfg, tos, subject, body, attachments)
    if os.environ.get("SENDGRID_API_KEY"):
        return _sendgrid(cfg, tos, subject, body, attachments)
    if os.environ.get("SMTP_HOST"):
        return _smtp(cfg, tos, subject, body, attachments)
    return {"ok": False, "dry_run": True, "to": tos, "subject": subject,
            "attachments": [str(a) for a in attachments],
            "error": "no email transport — set SMTP_HOST(+USER/PASSWORD) or RESEND_API_KEY / SENDGRID_API_KEY"}


def _smtp(cfg, tos, subject, body, attachments):
    msg = EmailMessage()
    msg["From"], msg["To"], msg["Subject"] = _from(cfg), ", ".join(tos), subject
    msg.set_content(body)
    for a in attachments:
        p = Path(a)
        if p.exists():
            msg.add_attachment(p.read_bytes(), maintype="application",
                               subtype="pdf" if p.suffix == ".pdf" else "octet-stream", filename=p.name)
    host, port = os.environ["SMTP_HOST"], int(os.environ.get("SMTP_PORT", 587))
    with smtplib.SMTP(host, port, timeout=30) as s:
        s.starttls()
        if os.environ.get("SMTP_USER"):
            s.login(os.environ["SMTP_USER"], os.environ.get("SMTP_PASSWORD", ""))
        s.send_message(msg)
    return {"ok": True, "transport": "smtp", "to": tos}


def _resend(cfg, tos, subject, body, attachments):
    payload = {"from": _from(cfg), "to": tos, "subject": subject, "text": body,
               "attachments": [{"filename": Path(a).name,
                                "content": base64.b64encode(Path(a).read_bytes()).decode()}
                               for a in attachments if Path(a).exists()]}
    req = urllib.request.Request("https://api.resend.com/emails", data=json.dumps(payload).encode(),
                                 method="POST", headers={"Authorization": f"Bearer {os.environ['RESEND_API_KEY']}",
                                                         "Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=30) as r:
        return {"ok": True, "transport": "resend", "to": tos, "id": json.load(r).get("id")}


def _sendgrid(cfg, tos, subject, body, attachments):
    payload = {"personalizations": [{"to": [{"email": t} for t in tos]}],
               "from": {"email": _from(cfg)}, "subject": subject,
               "content": [{"type": "text/plain", "value": body}],
               "attachments": [{"filename": Path(a).name, "type": "application/pdf",
                                "content": base64.b64encode(Path(a).read_bytes()).decode()}
                               for a in attachments if Path(a).exists()]}
    req = urllib.request.Request("https://api.sendgrid.com/v3/mail/send", data=json.dumps(payload).encode(),
                                 method="POST", headers={"Authorization": f"Bearer {os.environ['SENDGRID_API_KEY']}",
                                                         "Content-Type": "application/json"})
    urllib.request.urlopen(req, timeout=30)
    return {"ok": True, "transport": "sendgrid", "to": tos}


def email_report(cfg, pdf_path="report.pdf", subject=None, body=None):
    site = cfg.get("site", "your site")
    subject = subject or f"SEO report — {site}"
    body = body or (f"Attached is the latest SEO report for {site}, generated by the SEO pipeline.\n\n"
                    "It covers technical health, search performance, AI-search visibility, and the "
                    "prioritized action plan. Reply with questions.")
    return send(cfg, None, subject, body, attachments=[pdf_path])


def render_md(cfg, r):
    if r.get("ok"):
        return f"# Email sent ✅\n\n- via {r['transport']} to: {', '.join(r['to'])}"
    if r.get("dry_run"):
        return (f"# Email (dry run)\n\n- would send **{r['subject']}** to {', '.join(r['to'])} "
                f"with {len(r['attachments'])} attachment(s)\n- {r['error']}")
    return f"# Email failed\n\n- {r.get('error')}"
